language: java
script: mvn verify

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  slack:
    secure: "j6Zaxnwz/BM1NXijX6ZISpfSiEDXPT92pJ0u7PHafvyz9A3Ys8KexIBtYVgyyjaQLraZBqQH0ALq08XtJo9syznS3Wns4IPNDntZp6yVvfqVUdXaDes1Xt6zmAlLhq0RjU0TJeSeZIW6+xv0y4EoGswkFH21AoHonDvxjH/JJII="

